[package]
name = "calculator"
version = "0.1.0"
edition = "2021"
authors = ["Batazov Yura <leonyv04@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.14.0"